### ISSUE TITLE
WebSocket - 403 Forbidden

### ISSUE THREAD

**Issue by felipeavilis** [jitsi/skynet#203]
I'm trying to connect to Syknet using [streaming-whisper demo](https://github.com/jitsi/skynet/tree/dad315cb5706714299f4fa775d9baeaeca88f622/demos/streaming-whisper) but im getting 403. No idea why is happening.

LOGS
```
web-1    | 2025-04-28 16:52:10,950 uvicorn.error DEBUG:    = connection is CONNECTING
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < GET /streaming-whisper/ws/42ba0070-548e-431d-9304-8d0db1317083 HTTP/1.1
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < host: 10.5.10.4:8700
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < connection: Upgrade
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < pragma: no-cache
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < cache-control: no-cache
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
web-1    | 2025-04-28 16:52:10,951 uvicorn.error DEBUG:    < upgrade: websocket
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    < origin: http://127.0.0.1:5500
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    < sec-websocket-version: 13
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    < accept-encoding: gzip, deflate
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    < accept-language: pt-BR,pt;q=0.9,en;q=0.8
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    < sec-websocket-key: D+w4UaoY3HUgyLhKexqm4Q==
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    < sec-websocket-extensions: permessage-deflate; client_max_window_bits
web-1    | 2025-04-28 16:52:10,952 uvicorn.error INFO:     ('10.5.254.5', 64531) - "WebSocket /streaming-whisper/ws/42ba0070-548e-431d-9304-8d0db1317083" 403
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    > HTTP/1.1 403 Forbidden
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    > Date: Mon, 28 Apr 2025 16:52:10 GMT
web-1    | 2025-04-28 16:52:10,952 uvicorn.error DEBUG:    > Content-Length: 0
web-1    | 2025-04-28 16:52:10,953 uvicorn.error DEBUG:    > Content-Type: text/plain
web-1    | 2025-04-28 16:52:10,953 uvicorn.error DEBUG:    > Connection: close
web-1    | 2025-04-28 16:52:10,953 uvicorn.error DEBUG:    > [body] (0 bytes)
web-1    | 2025-04-28 16:52:10,953 uvicorn.error INFO:     connection rejected (403 Forbidden)
web-1    | 2025-04-28 16:52:10,953 uvicorn.error DEBUG:    x closing TCP connection
web-1    | 2025-04-28 16:52:10,953 uvicorn.error DEBUG:    = connection is CLOSED
web-1    | 2025-04-28 16:52:10,954 uvicorn.error INFO:     connection closed
```

docker-compose.yaml
```
services:
    web:
        image: skynet:latest
        environment:
            - BYPASS_AUTHORIZATION=true
            - REDIS_HOST=redis
        platform: linux/amd64
        ports:
            - 8700:8000
            - 8701:8001
            - 8703:8003
    redis:
        image: "redis:alpine"
        platform: linux/amd64
```
